Fix kms
awslabs/aws-nitro-enclaves-cose pull request #68
Opened 2023-10-02 16:17 UTC by petreeftime

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-03 19:08 UTC, belveryin approved these changes

2023-10-03 19:14 UTC, belveryin requested changes
`CI / Test on rust 1.66 (keys key_kms) (pull_request) ` doesn't pass, it requires `1.67` version of rust.

2023-10-04 05:50 UTC, petreeftime commented
Fixed, and also included a fix for the warnings regarding node12 deprecation for actions/checkout@v2.

2023-10-04 08:31 UTC, belveryin approved these changes

2023-10-04 12:21 UTC, merged